global:
  scrape_interval: 10s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node_exporter
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: api
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3333

  - job_name: mysql-exporter
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - mysql-exporter:9104
